### ISSUE TITLE
Invalid loader file for windows micro sd

### ISSUE THREAD

**Issue by IPIVAR** [jlobue10/SteamDeck_rEFInd#150]
Hello,

so i was trying to put dual booting with refind on my steamdeck so i could have windows and steamos and i dont know where i messed up but refind doesnt see or something windows 11 which is on mirco SD card  (winodws works fine from steam bios).
 
I seen someone with simmilar issue but he used windows on the one partition of the nvme  and am not really proficient with linux.
If someone could help it would be much appriciated. 

I will place few images down below for some refrence

![Image](https://github.com/user-attachments/assets/ed9a2a90-ce49-402a-87ec-9cf3684a4dfb)
![Image](https://github.com/user-attachments/assets/b6ce7c02-6c7a-4a7d-8d79-6ca2b6817fbc)
![Image](https://github.com/user-attachments/assets/728fc23a-34fd-4a3e-a411-779cebdce02a)

**Comment by jlobue10** [comment]
Can you please show me the output of `efibootmgr` and `lsblk -f`?

**Comment by IPIVAR** [comment]
Yes i can, here

<img width="2375" height="1182" alt="Image" src="https://github.com/user-attachments/assets/2219e227-19e9-4010-967d-f6a88625f9c5" />

<img width="2034" height="1179" alt="Image" src="https://github.com/user-attachments/assets/de9c9cd6-22e9-46f1-b29e-24fcd5d5f5c7" />

**Comment by jlobue10** [comment]
If you have installed the GUI version, please find the `refind.conf` file located in `/home/deck/.local/SteamDeck_rEFInd/GUI/` and edit the manual boot stanza for the Windows entry as follows.

```
menuentry "Windows" {
	icon /EFI/refind/os_icon2.png
        volume 1B21-2655
	loader /EFI/Microsoft/Boot/bootmgfw.efi
	graphics on
}
```

Save those changes and click on the install config option on the GUI. Type in your deck user password when prompted and reboot. All should be working fine afterwards if done correctly.

**Comment by IPIVAR** [comment]
I will put it inside that one and see how it goes.

**Comment by IPIVAR** [comment]
I tried putting the mentioned code into refind.conf file located in /home/deck/.local/SteamDeck_rEFInd/ and installed the config over the app, didn't fix it. Any other ideas?

**Comment by jlobue10** [comment]
Manually make the edit to the correct location of the installed file in command line with `sudo nano /esp/efi/refind/refind.conf` . Finish the changes, then press Ctrl+x followed by y and then enter. This should work if you edit the config file correctly.

**Comment by IPIVAR** [comment]
It was already set  like that...

<img width="1684" height="1128" alt="Image" src="https://github.com/user-attachments/assets/0508a49a-4bdf-45a8-ae93-585b82e825b3" />
